server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://172.19.241.28:3306/onlinepartern?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #rabbit配置
  rabbitmq:
    host: 172.19.241.1
    port: 5672
    username: root
    password: root


  #redis配置
  redis:
    host: 172.19.241.28
    database: 0
    port: 6379



mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.partern.bean

#showSql
logging:
  level:
    com:
      partern:
        mapper : debug

#自定义配置
head_img:
  file_prefix : op    #文件名前缀
  dir : /upload       #上传文件夹
  path : http://localhost:${server.port}${server.servlet.context-path}${headimg.dir}    #图片访问路径

